"""
enriched_samples.py  —  Option B (Dataset Enrichment)

Manually authored, hand-labelled sentences added to the original dataset.
NO external dataset is imported. Each entry is (text, label, category) where
`category` documents *why* the sample was added (the kind of difficulty or
diversity it introduces), satisfying "document every addition clearly".

Annotation guideline (kept consistent across all entries):
  - Label = the writer's OVERALL sentiment toward the product/service.
  - Sarcasm/irony is labelled by intended meaning, not surface words.
  - Mixed sentiment is labelled by the overall verdict; if perfectly balanced
    with no verdict, it is Neutral.
  - Factual statements, questions, and instructions carry no polarity -> Neutral.
"""

# (text, label, category)
ENRICHED = [
    # ---------------- POSITIVE (30 new, diverse + challenging) -------------
    ("Honestly didn't expect much, but this completely won me over.", "Positive", "negation_contrast"),
    ("It's not perfect, yet I'd buy it again in a heartbeat.", "Positive", "mixed_lean_positive"),
    ("The battery lasts forever and charging is lightning fast.", "Positive", "intensifier"),
    ("Way better than the model I had before.", "Positive", "comparative"),
    ("Setup took two minutes and everything just worked.", "Positive", "implicit"),
    ("Support actually called me back within the hour, rare these days.", "Positive", "implicit"),
    ("Five stars, no complaints whatsoever.", "Positive", "negation_phrasing"),
    ("I was skeptical, but the results speak for themselves.", "Positive", "contrast"),
    ("Smooth, quiet, and barely uses any power.", "Positive", "descriptive"),
    ("My whole team switched to it after seeing mine.", "Positive", "implicit_social_proof"),
    ("Can't fault it, does exactly what it promises.", "Positive", "negation_to_positive"),
    ("The update fixed every issue I had.", "Positive", "temporal"),
    ("Cheap price, premium feel.", "Positive", "contrast"),
    ("Held up perfectly after a year of daily use.", "Positive", "durability"),
    ("Even my technophobe dad figured it out instantly.", "Positive", "implicit"),
    ("Worth every penny and then some.", "Positive", "idiomatic"),
    ("Delivery was a day early, which never happens.", "Positive", "negation_context"),
    ("Crashes? Not once since I installed it.", "Positive", "negation_to_positive"),
    ("The screen is gorgeous in direct sunlight.", "Positive", "descriptive"),
    ("Customer service turned my bad week around.", "Positive", "contrast"),
    ("Lightweight enough to carry all day without noticing.", "Positive", "descriptive"),
    ("It paid for itself within a month.", "Positive", "implicit"),
    ("Quieter than a whisper and twice as fast.", "Positive", "comparative_intensifier"),
    ("I've recommended it to literally everyone.", "Positive", "implicit"),
    ("No regrets, best purchase this year.", "Positive", "negation_phrasing"),
    ("The app finally feels polished after the redesign.", "Positive", "temporal"),
    ("Tastes exactly like the real thing, maybe better.", "Positive", "comparative"),
    ("Returns were painless, refund hit my account same day.", "Positive", "positive_on_negative_topic"),
    ("Sturdy build, you can tell they didn't cut corners.", "Positive", "implicit"),
    ("Does the job beautifully and stays out of the way.", "Positive", "descriptive"),

    # ---------------- NEGATIVE (30 new, diverse + challenging) -------------
    ("Oh fantastic, another update that breaks everything.", "Negative", "sarcasm"),
    ("Looks nice, shame it stops working after a week.", "Negative", "mixed_lean_negative"),
    ("Not what I expected, and not in a good way.", "Negative", "negation"),
    ("Spent more time on hold than actually using it.", "Negative", "implicit"),
    ("The battery dies faster than my motivation on Mondays.", "Negative", "colloquial"),
    ("Worse than the cheap one it replaced.", "Negative", "comparative"),
    ("Sure, it works, if you enjoy waiting ten minutes to load.", "Negative", "sarcasm"),
    ("Great in theory, useless in practice.", "Negative", "contrast"),
    ("Three emails to support and still no reply.", "Negative", "implicit"),
    ("It overheats if you so much as look at it.", "Negative", "hyperbole"),
    ("Save your money and buy literally anything else.", "Negative", "advice"),
    ("The instructions might as well have been in another language.", "Negative", "implicit"),
    ("Stopped charging on day two. Day. Two.", "Negative", "emphasis"),
    ("Feels cheap, sounds cheap, is cheap.", "Negative", "repetition"),
    ("I wanted to love it, I really did.", "Negative", "implicit_disappointment"),
    ("The app logs me out every five minutes.", "Negative", "descriptive"),
    ("Paid for express shipping, arrived two weeks late.", "Negative", "contrast"),
    ("Half the features are locked behind a paywall.", "Negative", "descriptive"),
    ("Returned it the same day it arrived.", "Negative", "implicit"),
    ("Customer service hung up on me twice.", "Negative", "descriptive"),
    ("Louder than a jet engine and just as relaxing.", "Negative", "sarcasm_comparative"),
    ("It's fine, if your standards are on the floor.", "Negative", "sarcasm"),
    ("Buttons stopped responding within a month.", "Negative", "descriptive"),
    ("The 'waterproof' case leaked immediately.", "Negative", "irony_quotes"),
    ("Can't believe they charge money for this.", "Negative", "implicit"),
    ("Crashes constantly, support blames my phone.", "Negative", "descriptive"),
    ("Looks great in photos, falls apart in person.", "Negative", "mixed_lean_negative"),
    ("The free trial was the best part.", "Negative", "sarcasm_implicit"),
    ("Slower with every update, not faster.", "Negative", "negation_comparative"),
    ("Avoid unless you enjoy frustration.", "Negative", "advice"),

    # ---------------- NEUTRAL (70 new: factual / question / instruction) ----
    ("The package includes a charger, a cable, and a manual.", "Neutral", "factual"),
    ("It comes in three colors: black, white, and grey.", "Neutral", "factual"),
    ("The device weighs about two hundred grams.", "Neutral", "factual"),
    ("Shipping usually takes three to five business days.", "Neutral", "factual"),
    ("The app is available on both Android and iOS.", "Neutral", "factual"),
    ("It runs on two AA batteries.", "Neutral", "factual"),
    ("The warranty covers one year from purchase.", "Neutral", "factual"),
    ("You can change the language in the settings menu.", "Neutral", "instruction"),
    ("The screen measures six inches diagonally.", "Neutral", "factual"),
    ("The subscription renews automatically each month.", "Neutral", "factual"),
    ("There are two USB ports on the back.", "Neutral", "factual"),
    ("The manual is also available as a PDF online.", "Neutral", "factual"),
    ("It supports files up to two gigabytes.", "Neutral", "factual"),
    ("The store opens at nine and closes at six.", "Neutral", "factual"),
    ("The update is scheduled for next Tuesday.", "Neutral", "factual"),
    ("Each box contains twelve units.", "Neutral", "factual"),
    ("The software requires at least eight gigabytes of RAM.", "Neutral", "factual"),
    ("It connects over Bluetooth or Wi-Fi.", "Neutral", "factual"),
    ("The return window is thirty days.", "Neutral", "factual"),
    ("The model number is printed on the base.", "Neutral", "factual"),
    ("Does this come with a wall adapter?", "Neutral", "question"),
    ("Is the app free to download?", "Neutral", "question"),
    ("How long does the battery take to charge?", "Neutral", "question"),
    ("Can I use this outside the country?", "Neutral", "question"),
    ("What size should I order for a teenager?", "Neutral", "question"),
    ("Is there a version for Mac?", "Neutral", "question"),
    ("Do you ship to rural addresses?", "Neutral", "question"),
    ("When will the next model be released?", "Neutral", "question"),
    ("Are spare parts sold separately?", "Neutral", "question"),
    ("Which port is for the headphones?", "Neutral", "question"),
    ("If it freezes, hold the power button for ten seconds.", "Neutral", "instruction"),
    ("To reset it, press both buttons at once.", "Neutral", "instruction"),
    ("You'll need an adapter for European outlets.", "Neutral", "instruction"),
    ("Install the app before connecting the device.", "Neutral", "instruction"),
    ("Charge it fully before the first use.", "Neutral", "instruction"),
    ("Update the firmware to enable the new mode.", "Neutral", "instruction"),
    ("Keep the receipt in case you need to return it.", "Neutral", "instruction"),
    ("Pair it with the app to see usage stats.", "Neutral", "instruction"),
    ("Restart the router if the connection drops.", "Neutral", "instruction"),
    ("Register online to activate the warranty.", "Neutral", "instruction"),
    ("It's about the same size as a deck of cards.", "Neutral", "comparative_neutral"),
    ("The newer version looks identical to the old one.", "Neutral", "comparative_neutral"),
    ("It's roughly the price of a typical mid-range phone.", "Neutral", "comparative_neutral"),
    ("The interface is similar to the previous release.", "Neutral", "comparative_neutral"),
    ("It uses the same charger as the last model.", "Neutral", "comparative_neutral"),
    ("Compared spec for spec, the two are nearly identical.", "Neutral", "comparative_neutral"),
    ("The color in person matches the website.", "Neutral", "factual"),
    ("It's neither the cheapest nor the most expensive option.", "Neutral", "comparative_neutral"),
    ("I bought this for my office last March.", "Neutral", "context"),
    ("We use it mainly for video calls.", "Neutral", "context"),
    ("It replaced an older unit we'd had for years.", "Neutral", "context"),
    ("I ordered two, one for home and one for work.", "Neutral", "context"),
    ("The company is based in Germany.", "Neutral", "factual"),
    ("This is the second one I've owned.", "Neutral", "context"),
    ("It arrived in standard cardboard packaging.", "Neutral", "context"),
    ("I've been using it for about a week now.", "Neutral", "context"),
    ("The seller included a handwritten thank-you note.", "Neutral", "context"),
    ("It was a gift from my brother.", "Neutral", "context"),
    ("The firmware version is listed in the about page.", "Neutral", "factual"),
    ("I set it up over the weekend.", "Neutral", "context"),
    ("The buttons are arranged along the right edge.", "Neutral", "descriptive"),
    ("A small light blinks while it's charging.", "Neutral", "descriptive"),
    ("The fan turns on automatically under load.", "Neutral", "descriptive"),
    ("The cable is about one meter long.", "Neutral", "factual"),
    ("There's a headphone jack on the bottom.", "Neutral", "descriptive"),
    ("It ships from a warehouse in the next state.", "Neutral", "factual"),
    ("The default password is on the sticker underneath.", "Neutral", "instruction"),
    ("The box is sealed with tamper-evident tape.", "Neutral", "descriptive"),
    ("It supports up to five user profiles.", "Neutral", "factual"),
    ("The clock resets if you unplug it.", "Neutral", "descriptive"),
]

if __name__ == "__main__":
    from collections import Counter
    print("Enriched manual additions:", len(ENRICHED))
    print("By label:", dict(Counter(l for _, l, _ in ENRICHED)))
    print("Distinct categories:", len(set(c for _, _, c in ENRICHED)))
